### ISSUE TITLE
Credentials.h

### ISSUE THREAD

**Issue by stofakiller** [SensorsIot/ESP8266-RTC-Memory#1]
Hi,

As some of your other projects, credentials.h is missing so the code cant be compiled...

Please upload the file here and eg at espsensorhourly

Regards,
Jan

**Comment by Jim4Beam** [comment]
yap, missing code would be great! THANKS

**Comment by caiosweet** [comment]
1. In the user folder libraries, create a folder named "credentials".
2. Within the "credentials" folder create a file credentials.h
3. Open the "credentials.h" file and enter:

`#include "Arduino.h"`
`#define ASP_ssid "YOUR SSID" // SSID of your accesspoint`
`#define ASP_password "YOUR PASSWORD" // Password of Access Point`

4. Save and exit. 

Ps In this example Andreas Spiess has used ASP_ssid and ASP_password variables, but in other examples on github change. For example he uses "my_SSID my_PASSWORD" or "mySSID myPassword", in other words create your files "credentials.h" according to the variables included in the program. :O)

**Comment by DeanGreenhough** [comment]
Thank you caiosweet, you explanation was a great help
